# Generated by Django 5.2.4 on 2025-08-23 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='summerydb',
            new_name='summarydb',
        ),
        migrations.RenameField(
            model_name='summarydb',
            old_name='summery_text',
            new_name='summary_text',
        ),
    ]
